# Use OpenJDK 11 as the base image
FROM openjdk:11

# Expose port 8080
EXPOSE 8080

# Set the working directory to /app
WORKDIR /app

# Copy the Maven POM file to the container
COPY pom.xml .

# Copy the source code to the container
COPY src ./src

COPY target ./target

ADD target/APIJava-0.0.1-SNAPSHOT.jar APIJava-0.0.1-SNAPSHOT.jar

# Specify the entry point for the application
ENTRYPOINT ["java", "-jar", "target/APIJava-0.0.1-SNAPSHOT.jar"]

# Replace 'your-artifact-id' with the actual artifact ID generated by Maven
